services:
  - type: web
    name: owl-test
    runtime: static
    buildCommand: npm run build
    publishDirectory: dist
    staticPublishPath: /
    rewriteRules:
      - source: /*
        destination: /index.html
